version: '3.7'
services:
  db:
    image: mongo
    container_name: db
    env_file: ./db/env
    volumes:
      - "./db/data:/data/db"
    ports:
      - "27017:27017"
    networks:
      dropit:
        ipv4_address: 10.11.0.2
  backend:
    build:
      dockerfile: ./web/backend.Dockerfile
    env_file: ./web/backend/.env
    networks:
      dropit:
        ipv4_address: 10.11.0.3

networks:
  dropit:
    ipam:
      config:
        - subnet: 10.11.0.0/24
