apiVersion: v1
kind: Service
metadata:
  namespace: dropit
  labels:
    app: dropit-database
  name: dropit-database-service
spec:
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: dropit-database
  type: ClusterIP
